# Generated by Django 5.2.7 on 2025-10-30 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_info_Model',
            fields=[
                ('Student_Name', models.CharField(max_length=250, unique=True)),
                ('Student_Add_no', models.CharField(max_length=50, unique=True)),
                ('Student_Email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('Student_Phone', models.CharField(max_length=15)),
                ('Student_Position', models.CharField(max_length=100)),
                ('Student_Goal', models.CharField(blank=True, max_length=250, null=True)),
                ('Student_Dob', models.DateField(default='2010-08-10')),
                ('Student_Father', models.CharField(max_length=250)),
                ('Student_Address', models.CharField(max_length=250)),
                ('Student_Img', models.ImageField(upload_to='student/')),
                ('user_Stn', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Outreach_Programmes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Programme_name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=100)),
                ('Programme_Discription', models.TextField()),
                ('Programme_organiser', models.CharField(blank=True, max_length=200, null=True)),
                ('hosting_place', models.CharField(blank=True, max_length=200, null=True)),
                ('Programme_date', models.DateField()),
                ('Programme_img', models.ImageField(upload_to='outreach/')),
                ('stn_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.student_info_model')),
            ],
        ),
        migrations.CreateModel(
            name='Wings_Model',
            fields=[
                ('wing_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('wing_name', models.CharField(max_length=250, unique=True)),
                ('wing_email', models.CharField(max_length=250, unique=True)),
                ('wing_assistent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wing_helper', to='admin_panel.student_info_model')),
                ('wing_manager', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wing_chairPerson', to='admin_panel.student_info_model')),
            ],
        ),
    ]
